services:
  videoconferanceapp.server:
    image: videoconferanceapp.server
    build:
      context: .
      dockerfile: VideoConferanceApp.Server/Dockerfile

  videoconferanceapp.client:
    image: videoconferanceapp.client
    build:
      context: .
      dockerfile: VideoConferanceApp.Client/Dockerfile